{/*/app/layout.tsx*/}
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar"; // <-- new navbar import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      {/* <body className="bg-[#101820] text-white min-h-screen font-sans"> */}
      <body className="relative bg-[#101820] text-white min-h-screen font-sans overflow-y-auto">

        {/* Blobs / Custom background */}
        {/* Blobs background */}
        {/* <div className="absolute w-[200px] h-[200px] bg-[#0EA1D2FF] opacity-100 rounded-full z-0" style={{ top: "50%", left: "10%", filter: "blur(250px)" }} />
        <div className="absolute w-[200px] h-[200px] bg-[#B733E3FF] opacity-100 rounded-full z-0" style={{ top: "30%", left: "50%", filter: "blur(250px)" }} /> */}
        <Navbar /> {/*Navbar inserted here */}
        <main >{children}</main>
      </body>
    </html>
  );
}
